services:
  - type: worker
    name: telegram-pvp-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 src/main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: PLATFORM_TON_WALLET
        sync: false
      - key: TONCENTER_API_KEY
        sync: false
      - key: TON_WALLET_MNEMONIC
        sync: false
